### ISSUE TITLE
Style and color transfer issue

### ISSUE THREAD

**Issue by amoazeni75** [r4dl/LAENeRF#3]
Hi!

Thanks for your great work. 
I was able to successfully train your model on the Lego scene; while I was trying to follow the tutorial you have for using GUI and following the exact steps; I encountered a runtime error. Any thought for solving it would be appreciated!

`Exception has occurred: SystemError
<built-in function set_value> returned a result with an error set
  File "/home/samp8/projects/LAENeRF/nerf/gui.py", line 1913, in refresh_palet
    dpg.set_value('p0', self.palet[self.highlight_palette_id, 0])
  File "/home/samp8/projects/LAENeRF/nerf/gui.py", line 2028, in render
    self.refresh_palet()
  File "/home/samp8/projects/LAENeRF/main_nerf.py", line 250, in <module>
    gui.render()
SystemError: <built-in function set_value> returned a result with an error set`

**Comment by r4dl** [comment]
Hi,
can you outline what you were trying to do when the error occurred?
A possible issue might be that the color palette was not loaded correctly, but to reproduce it I'd need more info.
